### ISSUE TITLE
Memory Problem?

### ISSUE THREAD

**Issue by renqianluo** [jadore801120/attention-is-all-you-need-pytorch#25]
Hi, I clone your code and run train it on WMT English-German task, but it failed with `"RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1502009910772/work/torch/lib/THC/generic/THCStorage.cu:66".`
I run it on a Tesla K40 which has the same memory capacity of 12GB as your Titan X, and with the default settings.
So I don`t know why this happens, do you have any idea? Thanks

**Comment by alvations** [comment]
I'm getting the same error on a GTX 1080 with 8GB per card. 

```
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/torch/lib/THC/generic/THCStorage.cu:66
```

Error happens after training the first epoch when validation:

```
~/attention-is-all-you-need-pytorch$ python3 train.py -data data/multi30k.atok.low.pt -save_model trained -save_mode best -proj_share_weight 
Namespace(batch_size=64, cuda=True, d_inner_hid=1024, d_k=64, d_model=512, d_v=64, d_word_vec=512, data='data/multi30k.atok.low.pt', dropout=0.1, embs_share_weight=False, epoch=10, log=None, max_token_seq_len=52, n_head=8, n_layers=6, n_warmup_steps=4000, no_cuda=False, proj_share_weight=True, save_mode='best', save_model='trained', src_vocab_size=2909, tgt_vocab_size=3149)
[ Epoch 0 ]
  - (Training)   ppl:  102.10204, accuracy: 30.757 %, elapse: 2.077 min                                                 
  - (Validation) :   0%|                                                                         | 0/16 [00:00<?, ?it/s]THCudaCheck FAIL file=/pytorch/torch/lib/THC/generic/THCStorage.cu line=66 error=2 : out of memory
Traceback (most recent call last): 
```

**Comment by jadore801120** [comment]
Hi @renqianluo and @alvations,
Thanks for the report!
I also notice that the GPU memory usage is sometimes unacceptable huge.
I think part of the problem may be caused by history from the unnecessary enc-dec layer interaction pointed out in #27.
I will try to remove the incorrect layer interaction and observe the memory usage.
Thanks!

**Comment by jadore801120** [comment]
Hi @renqianluo and @alvations ,
This issue is to dealing with the memory problem just like #24 .
Let us discuss under one issue.
Thanks!

**Comment by jadore801120** [comment]
Hi @alvations ,
Thanks for pointing out the failing under the evaluation!
I modified the Variable preparing part in DataLoader.py to avoid recording history under evaluation.
I believe it will slightly mitigate the memory usage of evaluation.

Hi @renqianluo ,
As mentioned in #27, I implemented the model incorrectly by using all encode layer outputs and I think it may be part of the cause of the memory problem.
With the modification 07e2cda7d6e3ed9225ae1063b90a077432c24995, the recording of history is heavily reduced and there is no need to keep the layer outputs as local variable.
Under the default parameter settings, I run the model with ~8000MiB GPU memory usage. 
Please retry with the newest commit.

Thanks!

Yu-Hsiang

**Comment by renqianluo** [comment]
@jadore801120 Thanks for your response, I will try the new code

**Comment by akshay1123** [comment]
I am still getting out of memory error on latest commit in tesla P100, error occurs while validation starts after training in Epoch 1. @jadore801120  can you help me why is this error occuring even after optimization? Im pasting traceback below.

 - (Training)   ppl:  355.55811, accuracy: 21.974 %, elapse: 4.618 min
  - (Validation) :   0%|                                                                                                                                              | 0/32 [00:00<?, ?it/s]/root/home/intern4/data/transformer/DataLoader.py:119: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  torch.LongTensor(inst_data), volatile=self.test)
/root/home/intern4/data/transformer/DataLoader.py:121: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  torch.LongTensor(inst_position), volatile=self.test)
train.py:103: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  total_loss += loss.data[0]
THCudaCheck FAIL file=/pytorch/aten/src/THC/generic/THCStorage.cu line=58 error=2 : out of memory
Traceback (most recent call last):
  File "train.py", line 274, in <module>
    main()
  File "train.py", line 271, in main
    train(transformer, training_data, validation_data, crit, optimizer, opt)
  File "train.py", line 136, in train
    valid_loss, valid_accu = eval_epoch(model, validation_data, crit)
  File "train.py", line 96, in eval_epoch
    pred = model(src, tgt)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/home/intern4/data/transformer/transformer/Models.py", line 193, in forward
    dec_output, *_ = self.decoder(tgt_seq, tgt_pos, src_seq, enc_output)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/home/intern4/data/transformer/transformer/Models.py", line 131, in forward
    dec_enc_attn_mask=dec_enc_attn_pad_mask)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/home/intern4/data/transformer/transformer/Layers.py", line 33, in forward
    dec_input, dec_input, dec_input, attn_mask=slf_attn_mask)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/home/intern4/data/transformer/transformer/SubLayers.py", line 49, in forward
    q_s = q.repeat(n_head, 1, 1).view(n_head, -1, d_model) # n_head x (mb_size*len_q) x d_model
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/aten/src/THC/generic/THCStorage.cu:58

**Comment by DaoD** [comment]
@akshay1123 I'm not sure if you have solved your problem.
One hint for you, use torch.cuda.empty_cache() after every batch training. This may help, but I'm not sure.
You can monitor the memory allocated and cached periodically by torch:
torch.cuda.memory_allocated()
torch.cuda.memory_cached()

**Comment by BinWone** [comment]
> @akshay1123 I'm not sure if you have solved your problem.
> One hint for you, use torch.cuda.empty_cache() after every batch training. This may help, but I'm not sure.
> You can monitor the memory allocated and cached periodically by torch:
> torch.cuda.memory_allocated()
> torch.cuda.memory_cached()

use torch.cuda.empty_cache() still throw out of memory error, this didn't solve the problem. I can only use batch_size = 64 in 4 k40m GPUs, this train so slow, how can I use bigger batch_size? any suggestions? Thx!!!

**Comment by buptwhr** [comment]
> use torch.cuda.empty_cache() still throw out of memory error, this didn't solve the problem. I can only use batch_size = 64 in 4 k40m GPUs, this train so slow, how can I use bigger batch_size? any suggestions? Thx!!!

Have you solved this problem? That's so weird that only when my model is very small, there's no out of memory. But OOM happened again when the first epoch was trained 70%.

**Comment by DaoD** [comment]
@buptwhr I'm not sure since I haven't tried this project. Maybe you can use another project in the following link, which I have tried on my GPU, and there is no memory error. Hope this can help you.
https://github.com/DaoD/annotated-transformer

**Comment by jadore801120** [comment]
Dear all, 
Please take a look on the newest code.
I try to reduce as many the contiguous operations as possible with broadcasting.
Hope it helps. Thanks.
